version: '3'
services:
    web:
      build: .
      container_name: test
      command: bash -c "gunicorn --bind 0.0.0.0:5000 --workers 2 wsgi:app"
      volumes:
        - ./src:/src
      ports:
        - 5000:5000


     #expose:  так как задание без NGINX  то не импользуем EXPOSE
       # - "5000"